spring.application.name=baozi
spring.datasource.url=jdbc:mysql://localhost:3306/baozi
spring.datasource.username=root
spring.datasource.password=MYSQL123_senha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true